import tkinter as tk
form = tk.Tk()
form.title('Tkinter Dersleri Formu')
label = tk.Label(form,text = 'Python Tkinter')
label.pack()
label2 = tk.Label(form,text='Ders-2-',fg='red')
label2.pack()
label3 = tk.Label(form,text = 'Ders-2 background',fg = 'black',bg = 'green')
label3.pack()
label4 = tk.Label(form,text = 'yeni label',fg='red',bg = 'green',font = 'Times 15 italic')
label4.pack()
label5 = tk.Label(form,text = 'En son Label',fg = 'green', bg = 'red',font='Times 17 bold')
label5.pack()
form.mainloop()
